### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by abnerzhao** [abnerzhao/flag#10]
## Book

- [ ] [凤凰架构](http://icyfenix.cn/)
- [ ] [Spring 实战（第5版 ）](https://book.douban.com/subject/34949443/)
- [ ] [Spring Boot 实战](https://book.douban.com/subject/34949443/)
- [ ] [置身事内](https://book.douban.com/subject/35546622/)
- [x] [UNIX传奇](https://book.douban.com/subject/35292726/) (4.3)
  - Unix 的诞生离不开优秀的人才和组织，当时的贝尔实验室简直就是技术大佬们的天堂
- [x] [午夜降临前抵达](https://book.douban.com/subject/35522033/)(3.27)
  -  兼具游记的趣味性和浓厚的人文气息
- [x] [胖虎下山](https://book.douban.com/subject/35701255/) (3.15)
  - 简直不要太治愈
- [x] [底层逻辑](https://book.douban.com/subject/35620025/) (3.15)
  - 学废了
- [x] [他改变了中国](https://book.douban.com/subject/1023322/) (2.20)
  - 1992-2002 风云变幻，折服于长者的智慧和人格魅力
- [x] [阿里巴巴 Java 开发手册](https://book.douban.com/subject/27605355/) (2.16)
  - 入门必读，类似 Effective 系列
- [x] [邓小平时代](https://book.douban.com/subject/20424526/) (1.15)
  - 三起三落，传奇一生

**Comment by abnerzhao** [comment]
## Tech

- [ ] Kafka
- RPC
  - [ ] Thrift
  - [ ] gRPC
- [ ] ES
- [ ] [Java 全栈知识体系](https://pdai.tech/md/java/basic/java-basic-x-generic.html)
